server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

spring:
  application:
    name: server-gateway
  sleuth:
    web:
      client:
        enabled: true
      sampler:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  cloud:
    gateway:
      routes:
      - id: adminapi
        uri: lb://monitor-service
        predicates:
        - Path=/monitor/**
        filters:
        - StripPrefix=1
      - id: adminapi
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
  boot:
    admin:
      client:
        url: http://localhost:8903/


  management:
    endpoints:
      web:
        exposure:
          include: "*"